
### Forest plots ----
# Auckland
png("AucklandForestVHT.png", width = 6, height = 10.63, units = "in", res = 300)
pred_forest_vht("Auckland")
dev.off()
png("AucklandForestNurse.png", width = 3.7, height = 10.63, units = "in", res = 300)
pred_forest_nurse("Auckland")
dev.off()
png("AucklandForestSDQT.png", width = 6, height = 10.63, units = "in", res = 300)
pred_forest_sdqt("Auckland")
dev.off()

# Bay of Plenty
png("BayofPlentyForestVHT.png", width = 6, height = 10.63, units = "in", res = 300)
pred_forest_vht_1("Bay of Plenty")
dev.off()
png("BayofPlentyForestNurse.png", width = 3.7, height = 10.63, units = "in", res = 300)
pred_forest_nurse_1("Bay of Plenty")
dev.off()
png("BayofPlentyForestSDQT.png", width = 6, height = 10.63, units = "in", res = 300)
pred_forest_sdqt_1("Bay of Plenty")
dev.off()

# Canterbury
png("CanterburyForestVHT.png", width = 6, height = 10.63, units = "in", res = 300)
pred_forest_vht_2("Canterbury")
dev.off()
png("CanterburyForestNurse.png", width = 3.7, height = 10.63, units = "in", res = 300)
pred_forest_nurse_2("Canterbury")
dev.off()
png("CanterburyForestSDQT.png", width = 6, height = 10.63, units = "in", res = 300)
pred_forest_sdqt_2("Canterbury")
dev.off()

# Capital and Coast
png("CapitalandCoastForestVHT.png", width = 6, height = 10.63, units = "in", res = 300)
pred_forest_vht_2("Capital and Coast")
dev.off()
png("CapitalandCoastForestNurse.png", width = 3.7, height = 10.63, units = "in", res = 300)
pred_forest_nurse_2("Capital and Coast")
dev.off()
png("CapitalandCoastForestSDQT.png", width = 6, height = 10.63, units = "in", res = 300)
pred_forest_sdqt_2("Capital and Coast")
dev.off()

# Counties Manukau
png("CountiesManukauForestVHT.png", width = 6, height = 10.63, units = "in", res = 300)
pred_forest_vht("Counties Manukau")
dev.off()
png("CountiesManukauForestNurse.png", width = 3.7, height = 10.63, units = "in", res = 300)
pred_forest_nurse("Counties Manukau")
dev.off()
png("CountiesManukauForestSDQT.png", width = 6, height = 10.63, units = "in", res = 300)
pred_forest_sdqt("Counties Manukau")
dev.off()

# Hawke's Bay
png("HawkesBayForestVHT.png", width = 6, height = 10.63, units = "in", res = 300)
pred_forest_vht_3("Hawkes Bay")
dev.off()
png("HawkesBayForestNurse.png", width = 3.7, height = 10.63, units = "in", res = 300)
pred_forest_nurse_3("Hawkes Bay")
dev.off()
png("HawkesBayForestSDQT.png", width = 6, height = 10.63, units = "in", res = 300)
pred_forest_sdqt_3("Hawkes Bay")
dev.off()

# Hutt Valley
png("HuttValleyForestVHT.png", width = 6, height = 10.63, units = "in", res = 300)
pred_forest_vht_1("Hutt Valley")
dev.off()
png("HuttValleyForestNurse.png", width = 3.7, height = 10.63, units = "in", res = 300)
pred_forest_nurse_1("Hutt Valley")
dev.off()
png("HuttValleyForestSDQT.png", width = 6, height = 10.63, units = "in", res = 300)
pred_forest_sdqt_1("Hutt Valley")
dev.off()

# Lakes
png("LakesForestVHT.png", width = 6, height = 10.63, units = "in", res = 300)
pred_forest_vht_4("Lakes")
dev.off()
png("LakesForestNurse.png", width = 3.7, height = 10.63, units = "in", res = 300)
pred_forest_nurse_4("Lakes")
dev.off()
png("LakesForestSDQT.png", width = 6, height = 10.63, units = "in", res = 300)
pred_forest_sdqt_4("Lakes")
dev.off()

# MidCentral
png("MidCentralForestVHT.png", width = 6, height = 10.63, units = "in", res = 300)
pred_forest_vht_5("MidCentral")
dev.off()
png("MidCentralForestNurse.png", width = 3.7, height = 10.63, units = "in", res = 300)
pred_forest_nurse_5("MidCentral")
dev.off()
png("MidCentralForestSDQT.png", width = 6, height = 10.63, units = "in", res = 300)
pred_forest_sdqt_5("MidCentral")
dev.off()

# Nelson Marlborough
png("NelsonMarlboroughForestVHT.png", width = 6, height = 10.63, units = "in", res = 300)
pred_forest_vht_1("Nelson Marlborough")
dev.off()
png("NelsonMarlboroughForestNurse.png", width = 3.7, height = 10.63, units = "in", res = 300)
pred_forest_nurse_1("Nelson Marlborough")
dev.off()
png("NelsonMarlboroughForestSDQT.png", width = 6, height = 10.63, units = "in", res = 300)
pred_forest_sdqt_1("Nelson Marlborough")
dev.off()

# Northland
png("NorthlandForestVHT.png", width = 6, height = 10.63, units = "in", res = 300)
pred_forest_vht("Northland")
dev.off()
png("NorthlandForestNurse.png", width = 3.7, height = 10.63, units = "in", res = 300)
pred_forest_nurse("Northland")
dev.off()
png("NorthlandForestSDQT.png", width = 6, height = 10.63, units = "in", res = 300)
pred_forest_sdqt("Northland")
dev.off()

# South Canterbury
png("SouthCanterburyForestVHT.png", width = 6, height = 10.63, units = "in", res = 300)
pred_forest_vht_6("South Canterbury")
dev.off()
png("SouthCanterburyForestNurse.png", width = 3.7, height = 10.63, units = "in", res = 300)
pred_forest_nurse_6("South Canterbury")
dev.off()
png("SouthCanterburyForestSDQT.png", width = 6, height = 10.63, units = "in", res = 300)
pred_forest_sdqt_6("South Canterbury")
dev.off()

# Southern
png("SouthernForestVHT.png", width = 6, height = 10.63, units = "in", res = 300)
pred_forest_vht_5("Southern")
dev.off()
png("SouthernForestNurse.png", width = 3.7, height = 10.63, units = "in", res = 300)
pred_forest_nurse_5("Southern")
dev.off()
png("SouthernForestSDQT.png", width = 6, height = 10.63, units = "in", res = 300)
pred_forest_sdqt_5("Southern")
dev.off()

# Tairawhiti
png("TairawhitiForestVHT.png", width = 6, height = 10.63, units = "in", res = 300)
pred_forest_vht_7("Tairawhiti")
dev.off()
png("TairawhitiForestNurse.png", width = 3.7, height = 10.63, units = "in", res = 300)
pred_forest_nurse_7("Tairawhiti")
dev.off()
png("TairawhitiForestSDQT.png", width = 6, height = 10.63, units = "in", res = 300)
pred_forest_sdqt_7("Tairawhiti")
dev.off()

# Taranaki
png("TaranakiForestVHT.png", width = 6, height = 10.63, units = "in", res = 300)
pred_forest_vht_8("Taranaki")
dev.off()
png("TaranakiForestNurse.png", width = 3.7, height = 10.63, units = "in", res = 300)
pred_forest_nurse_8("Taranaki")
dev.off()
png("TaranakiForestSDQT.png", width = 6, height = 10.63, units = "in", res = 300)
pred_forest_sdqt_8("Taranaki")
dev.off()

# Waikato
png("WaikatoForestVHT.png", width = 6, height = 10.63, units = "in", res = 300)
pred_forest_vht_9("Waikato")
dev.off()
png("WaikatoForestNurse.png", width = 3.7, height = 10.63, units = "in", res = 300)
pred_forest_nurse_9("Waikato")
dev.off()
png("WaikatoForestSDQT.png", width = 6, height = 10.63, units = "in", res = 300)
pred_forest_sdqt_9("Waikato")
dev.off()

# Wairarapa
png("WairarapaForestVHT.png", width = 6, height = 10.63, units = "in", res = 300)
pred_forest_vht_10("Wairarapa")
dev.off()
png("WairarapaForestNurse.png", width = 3.7, height = 10.63, units = "in", res = 300)
pred_forest_nurse_10("Wairarapa")
dev.off()
png("WairarapaForestSDQT.png", width = 6, height = 10.63, units = "in", res = 300)
pred_forest_sdqt_10("Wairarapa")
dev.off()

# Waitemata
png("WaitemataForestVHT.png", width = 6, height = 10.63, units = "in", res = 300)
pred_forest_vht_11("Waitemata")
dev.off()
png("WaitemataForestNurse.png", width = 3.7, height = 10.63, units = "in", res = 300)
pred_forest_nurse_11("Waitemata")
dev.off()
png("WaitemataForestSDQT.png", width = 6, height = 10.63, units = "in", res = 300)
pred_forest_sdqt_11("Waitemata")
dev.off()

# West Coast
png("WestCoastForestVHT.png", width = 6, height = 10.63, units = "in", res = 300)
pred_forest_vht_12("West Coast")
dev.off()
png("WestCoastForestNurse.png", width = 3.7, height = 10.63, units = "in", res = 300)
pred_forest_nurse_12("West Coast")
dev.off()
png("WestCoastForestSDQT.png", width = 6, height = 10.63, units = "in", res = 300)
pred_forest_sdqt_12("West Coast")
dev.off()

# Whanganui
png("WhanganuiForestVHT.png", width = 6, height = 10.63, units = "in", res = 300)
pred_forest_vht_8("Whanganui")
dev.off()
png("WhanganuiForestNurse.png", width = 3.7, height = 10.63, units = "in", res = 300)
pred_forest_nurse_8("Whanganui")
dev.off()
png("WhanganuiForestSDQT.png", width = 6, height = 10.63, units = "in", res = 300)
pred_forest_sdqt_8("Whanganui")
dev.off()


### Attendance plots ----
# Auckland
png("AucklandVHT.png", width = 10.39, height = 7.56, units = "in", res = 300)
myplot_vht("Auckland")
dev.off()
png("AucklandNurse.png", width = 10.39, height = 7.56, units = "in", res = 300)
myplot_nurse("Auckland")
dev.off()
png("AucklandSDQT.png", width = 10.39, height = 7.56, units = "in", res = 300)
myplot_sdqt("Auckland")
dev.off()

# Bay of Plenty
png("BayofPlentyVHT.png", width = 10.39, height = 7.56, units = "in", res = 300)
myplot_vht("Bay of Plenty")
dev.off()
png("BayofPlentyNurse.png", width = 10.39, height = 7.56, units = "in", res = 300)
myplot_nurse("Bay of Plenty")
dev.off()
png("BayofPlentySDQT.png", width = 10.39, height = 7.56, units = "in", res = 300)
myplot_sdqt("Bay of Plenty")
dev.off()

# Canterbury
png("CanterburyVHT.png", width = 10.39, height = 7.56, units = "in", res = 300)
myplot_vht("Canterbury")
dev.off()
png("CanterburyNurse.png", width = 10.39, height = 7.56, units = "in", res = 300)
myplot_nurse("Canterbury")
dev.off()
png("CanterburySDQT.png", width = 10.39, height = 7.56, units = "in", res = 300)
myplot_sdqt("Canterbury")
dev.off()

# Capital and Coast
png("CapitalandCoastVHT.png", width = 10.39, height = 7.56, units = "in", res = 300)
myplot_vht("Capital and Coast")
dev.off()
png("CapitalandCoastNurse.png", width = 10.39, height = 7.56, units = "in", res = 300)
myplot_nurse("Capital and Coast")
dev.off()
png("CapitalandCoastSDQT.png", width = 10.39, height = 7.56, units = "in", res = 300)
myplot_sdqt("Capital and Coast")
dev.off()

# Counties Manukau
png("CountiesManukauVHT.png", width = 9.53, height = 6.93, units = "in", res = 300)
myplot_vht("Counties Manukau")
dev.off()
png("CountiesManukauNurse.png", width = 9.53, height = 6.93, units = "in", res = 300)
myplot_nurse("Counties Manukau")
dev.off()
png("CountiesManukauSDQT.png", width = 9.53, height = 6.93, units = "in", res = 300)
myplot_sdqt("Counties Manukau")
dev.off()

# Hawke's Bay
png("HawkesBayVHT.png", width = 9.53, height = 6.93, units = "in", res = 300)
myplot_vht("Hawke's Bay")
dev.off()
png("HawkesBayNurse.png", width = 9.53, height = 6.93, units = "in", res = 300)
myplot_nurse("Hawke's Bay")
dev.off()
png("HawkesBaySDQT.png", width = 9.53, height = 6.93, units = "in", res = 300)
myplot_sdqt("Hawke's Bay")
dev.off()

# Hutt Valley
png("Hutt ValleyVHT.png", width = 9.53, height = 6.93, units = "in", res = 300)
myplot_vht("Hutt Valley")
dev.off()
png("Hutt ValleyNurse.png", width = 9.53, height = 6.93, units = "in", res = 300)
myplot_nurse("Hutt Valley")
dev.off()
png("Hutt ValleySDQT.png", width = 9.53, height = 6.93, units = "in", res = 300)
myplot_sdqt("Hutt Valley")
dev.off()

# Lakes
png("LakesVHT.png", width = 9.53, height = 6.93, units = "in", res = 300)
myplot_vht("Lakes")
dev.off()
png("LakesNurse.png", width = 9.53, height = 6.93, units = "in", res = 300)
myplot_nurse("Lakes")
dev.off()
png("LakesSDQT.png", width = 9.53, height = 6.93, units = "in", res = 300)
myplot_sdqt("Lakes")
dev.off()

# MidCentral
png("MidCentralVHT.png", width = 9.53, height = 6.93, units = "in", res = 300)
myplot_vht("MidCentral")
dev.off()
png("MidCentralNurse.png", width = 9.53, height = 6.93, units = "in", res = 300)
myplot_nurse("MidCentral")
dev.off()
png("MidCentralSDQT.png", width = 9.53, height = 6.93, units = "in", res = 300)
myplot_sdqt("MidCentral")
dev.off()

# Nelson Marlborough
png("NelsonMarlboroughVHT.png", width = 8.66, height = 6.3, units = "in", res = 300)
myplot_vht("Nelson Marlborough")
dev.off()
png("NelsonMarlboroughNurse.png", width = 8.66, height = 6.3, units = "in", res = 300)
myplot_nurse("Nelson Marlborough")
dev.off()
png("NelsonMarlboroughSDQT.png", width = 8.66, height = 6.3, units = "in", res = 300)
myplot_sdqt("Nelson Marlborough")
dev.off()

# Northland
png("NorthlandVHT.png", width = 8.66, height = 6.3, units = "in", res = 300)
myplot_vht("Northland")
dev.off()
png("NorthlandNurse.png", width = 8.66, height = 6.3, units = "in", res = 300)
myplot_nurse("Northland")
dev.off()
png("NorthlandSDQT.png", width = 8.66, height = 6.3, units = "in", res = 300)
myplot_sdqt("Northland")
dev.off()

# South Canterbury
png("SouthCanterburyVHT.png", width = 8.66, height = 6.3, units = "in", res = 300)
myplot_vht("South Canterbury")
dev.off()
png("SouthCanterburyNurse.png", width = 8.66, height = 6.3, units = "in", res = 300)
myplot_nurse("South Canterbury")
dev.off()
png("SouthCanterburySDQT.png", width = 8.66, height = 6.3, units = "in", res = 300)
myplot_sdqt("South Canterbury")
dev.off()

# Southern
png("SouthernVHT.png", width = 8.66, height = 6.3, units = "in", res = 300)
myplot_vht("Southern")
dev.off()
png("SouthernNurse.png", width = 8.66, height = 6.3, units = "in", res = 300)
myplot_nurse("Southern")
dev.off()
png("SouthernSDQT.png", width = 8.66, height = 6.3, units = "in", res = 300)
myplot_sdqt("Southern")
dev.off()

# Tairawhiti
png("TairawhitiVHT.png", width = 8.66, height = 6.3, units = "in", res = 300)
myplot_vht("Tairawhiti")
dev.off()
png("TairawhitiNurse.png", width = 8.66, height = 6.3, units = "in", res = 300)
myplot_nurse("Tairawhiti")
dev.off()
png("TairawhitiSDQT.png", width = 8.66, height = 6.3, units = "in", res = 300)
myplot_sdqt("Tairawhiti")
dev.off()

# Taranaki
png("TaranakiVHT.png", width = 8.66, height = 6.3, units = "in", res = 300)
myplot_vht("Taranaki")
dev.off()
png("TaranakiNurse.png", width = 8.66, height = 6.3, units = "in", res = 300)
myplot_nurse("Taranaki")
dev.off()
png("TaranakiSDQT.png", width = 8.66, height = 6.3, units = "in", res = 300)
myplot_sdqt("Taranaki")
dev.off()

# Waikato
png("WaikatoVHT.png", width = 11.26, height = 8.19, units = "in", res = 300)
myplot_vht("Waikato")
dev.off()
png("WaikatoNurse.png", width = 11.26, height = 8.19, units = "in", res = 300)
myplot_nurse("Waikato")
dev.off()
png("WaikatoSDQT.png", width = 11.26, height = 8.19, units = "in", res = 300)
myplot_sdqt("Waikato")
dev.off()

# Wairarapa
png("WairarapaVHT.png", width = 8.66, height = 6.3, units = "in", res = 300)
myplot_vht("Wairarapa")
dev.off()
png("WairarapaNurse.png", width = 8.66, height = 6.3, units = "in", res = 300)
myplot_nurse("Wairarapa")
dev.off()
png("WairarapaSDQT.png", width = 8.66, height = 6.3, units = "in", res = 300)
myplot_sdqt("Wairarapa")
dev.off()

# Waitemata
png("WaitemataVHT.png", width = 8.66, height = 6.3, units = "in", res = 300)
myplot_vht("Waitemata")
dev.off()
png("WaitemataNurse.png", width = 8.66, height = 6.3, units = "in", res = 300)
myplot_nurse("Waitemata")
dev.off()
png("WaitemataSDQT.png", width = 8.66, height = 6.3, units = "in", res = 300)
myplot_sdqt("Waitemata")
dev.off()

# West Coast
png("WestCoastVHT.png", width = 8.66, height = 6.3, units = "in", res = 300)
myplot_vht("West Coast")
dev.off()
png("WestCoastNurse.png", width = 8.66, height = 6.3, units = "in", res = 300)
myplot_nurse("West Coast")
dev.off()
png("WestCoastSDQT.png", width = 8.66, height = 6.3, units = "in", res = 300)
myplot_sdqt("West Coast")
dev.off()

# Whaganui
png("WhanganuiVHT.png", width = 8.66, height = 6.3, units = "in", res = 300)
myplot_vht("Whanganui")
dev.off()
png("WhanganuiNurse.png", width = 8.66, height = 6.3, units = "in", res = 300)
myplot_nurse("Whanganui")
dev.off()
png("WhanganuiSDQT.png", width = 8.66, height = 6.3, units = "in", res = 300)
myplot_sdqt("Whanganui")
dev.off()

# LB
png("AucklandVHTbyLB.png", width = 8.66, height = 6.3, units = "in", res = 300)
myplot_vht_lb("Auckland")
dev.off()
png("WaitemataVHTbyLB.png", width = 8.66, height = 6.3, units = "in", res = 300)
myplot_vht_lb_1("Waitemata")
dev.off()
png("CountiesManukauVHTbyLB.png", width = 8.66, height = 6.3, units = "in", res = 300)
myplot_vht_lb("Counties Manukau")
dev.off()

png("AucklandNursebyLB.png", width = 8.66, height = 6.3, units = "in", res = 300)
myplot_nurse_lb("Auckland")
dev.off()
png("WaitemataNursebyLB.png", width = 8.66, height = 6.3, units = "in", res = 300)
myplot_nurse_lb_1("Waitemata")
dev.off()
png("CountiesManukauNursebyLB.png", width = 8.66, height = 6.3, units = "in", res = 300)
myplot_nurse_lb("Counties Manukau")
dev.off()

png("AucklandSDQTbyLB.png", width = 8.66, height = 6.3, units = "in", res = 300)
myplot_sdqt_lb("Auckland")
dev.off()
png("WaitemataSDQTbyLB.png", width = 8.66, height = 6.3, units = "in", res = 300)
myplot_sdqt_lb("Waitemata")
dev.off()
png("CountiesManukauSDQTbyLB.png", width = 8.66, height = 6.3, units = "in", res = 300)
myplot_sdqt_lb("Counties Manukau")
dev.off()

### Composition plots ----
png("AucklandCompForest.png", width = 10, height = 6.5, unit = "in", res = 300)
comp_top_pred("Auckland")
dev.off()

png("BayofPlentyCompForest.png", width = 10, height = 6.5, unit = "in", res = 300)
comp_top_pred("Bay of Plenty")
dev.off()

png("CanterburyCompForest.png", width = 10, height = 6.5, unit = "in", res = 300)
comp_top_pred("Canterbury")
dev.off()

png("CapitalandCoastCompForest.png", width = 10, height = 6.5, unit = "in", res = 300)
comp_top_pred("Capital and Coast")
dev.off()

png("CountiesManukauCompForest.png", width = 10, height = 6.5, unit = "in", res = 300)
comp_top_pred("Counties Manukau")
dev.off()

png("HawkesBayCompForest.png", width = 10, height = 6.5, unit = "in", res = 300)
comp_top_pred("Hawkes Bay")
dev.off()

png("HuttValleyCompForest.png", width = 10, height = 6.5, unit = "in", res = 300)
comp_top_pred("Hutt Valley")
dev.off()

png("LakesCompForest.png", width = 10, height = 6.5, unit = "in", res = 300)
comp_top_pred("Lakes")
dev.off()

png("MidCentralCompForest.png", width = 10, height = 6.5, unit = "in", res = 300)
comp_top_pred("MidCentral")
dev.off()

png("NelsonMarlboroughCompForest.png", width = 10, height = 6.5, unit = "in", res = 300)
comp_top_pred("Nelson Marlborough")
dev.off()

png("NorthlandCompForest.png", width = 10, height = 6.5, unit = "in", res = 300)
comp_top_pred("Northland")
dev.off()

png("SouthCanterburyCompForest.png", width = 10, height = 6.5, unit = "in", res = 300)
comp_top_pred("South Canterbury")
dev.off()

png("SouthernCompForest.png", width = 10, height = 6.5, unit = "in", res = 300)
comp_top_pred("Southern")
dev.off()

png("TairawhitiCompForest.png", width = 10, height = 6.5, unit = "in", res = 300)
comp_top_pred("Tairawhiti")
dev.off()

png("TaranakiCompForest.png", width = 10, height = 6.5, unit = "in", res = 300)
comp_top_pred("Taranaki")
dev.off()

png("WaikatoCompForest.png", width = 10, height = 6.5, unit = "in", res = 300)
comp_top_pred("Waikato")
dev.off()

png("WairarapaCompForest.png", width = 10, height = 6.5, unit = "in", res = 300)
comp_top_pred("Wairarapa")
dev.off()

png("WaitemataCompForest.png", width = 10, height = 6.5, unit = "in", res = 300)
comp_top_pred("Waitemata")
dev.off()

png("WestCoastCompForest.png", width = 10, height = 6.5, unit = "in", res = 300)
comp_top_pred("West Coast")
dev.off()

png("WhanganuiCompForest.png", width = 10, height = 6.5, unit = "in", res = 300)
comp_top_pred("Whanganui")
dev.off()


### Char tables ----
chartable("Auckland")
chartable("Bay of Plenty")
chartable("Canterbury")
chartable("Capital and Coast")
chartable("Counties Manukau")
chartable("Hawke's Bay")
chartable("Hutt Valley")
chartable("Lakes")
chartable("MidCentral")
chartable("Nelson Marlborough")
chartable("Northland")
chartable("South Canterbury")
chartable("Southern")
chartable("Tairawhiti")
chartable("Taranaki")
chartable("Waikato")
chartable("Wairarapa")
chartable("Waitemata")
chartable("West Coast")
chartable("Whanganui")

# LB
chartable_lb("Auckland")
chartable_lb("Waitemata")
chartable_lb("Counties Manukau")

